# Generated by Django 5.2.8 on 2025-12-12 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('passport_id', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=150)),
                ('specialization', models.CharField(max_length=150)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('desired_position', models.CharField(max_length=150)),
                ('desired_salary', models.PositiveIntegerField()),
                ('about', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employ', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
