# Generated by Django 5.2.8 on 2025-12-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='enter name of student')),
                ('age', models.PositiveIntegerField(default=17, verbose_name='enter age of student')),
                ('certifivate', models.FileField(upload_to='documents/', verbose_name='dowloand certificate')),
                ('ORT_test', models.URLField(verbose_name='enter results of ORT')),
                ('directions', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('UI/UX', 'UI/UX'), ('not defenetetly', '')], default='Backend', max_length=100, verbose_name='choose the directions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
    ]
