# Generated by Django 5.2.8 on 2025-12-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutyou',
            name='photo',
            field=models.ImageField(null=True, upload_to='news/', verbose_name='загрузите основное фото'),
        ),
        migrations.AlterField(
            model_name='aboutyou',
            name='day_birth',
            field=models.IntegerField(max_length=2, verbose_name='enter your day birth'),
        ),
        migrations.AlterField(
            model_name='aboutyou',
            name='height',
            field=models.IntegerField(verbose_name='enter your height'),
        ),
        migrations.AlterField(
            model_name='aboutyou',
            name='regret_moment',
            field=models.TextField(default='ssentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lor', max_length=500, verbose_name='ener your moment'),
        ),
        migrations.AlterField(
            model_name='aboutyou',
            name='weight',
            field=models.IntegerField(verbose_name='enter youw weight'),
        ),
        migrations.AlterField(
            model_name='aboutyou',
            name='your_name',
            field=models.CharField(max_length=100, verbose_name='enter your name'),
        ),
    ]
