# Generated by Django 5.2.8 on 2025-12-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_aboutyou_photo_alter_aboutyou_day_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutyou',
            name='day_birth',
            field=models.IntegerField(verbose_name='enter your day birth'),
        ),
        migrations.AlterField(
            model_name='aboutyou',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='загрузите основное фото'),
        ),
        migrations.AlterField(
            model_name='aboutyou',
            name='regret_moment',
            field=models.TextField(default='', max_length=500, verbose_name='enter your moment'),
        ),
        migrations.AlterField(
            model_name='aboutyou',
            name='weight',
            field=models.IntegerField(verbose_name='enter your weight'),
        ),
    ]
