# Generated by Django 5.2.8 on 2025-12-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_aboutyou_day_birth_alter_aboutyou_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutyou',
            name='day_birth',
        ),
        migrations.RemoveField(
            model_name='aboutyou',
            name='height',
        ),
        migrations.RemoveField(
            model_name='aboutyou',
            name='regret_moment',
        ),
        migrations.RemoveField(
            model_name='aboutyou',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='aboutyou',
            name='your_name',
        ),
        migrations.AddField(
            model_name='aboutyou',
            name='author',
            field=models.CharField(default='unknown', max_length=100, verbose_name='enter author this book'),
        ),
        migrations.AddField(
            model_name='aboutyou',
            name='day_made',
            field=models.IntegerField(default=2000, verbose_name='when was created this book'),
        ),
        migrations.AddField(
            model_name='aboutyou',
            name='discription',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='enter your moment'),
        ),
        migrations.AddField(
            model_name='aboutyou',
            name='jenre',
            field=models.TextField(default='romcom', verbose_name='enter jenre'),
        ),
        migrations.AddField(
            model_name='aboutyou',
            name='pages',
            field=models.IntegerField(default=200, verbose_name='enter how many pages'),
        ),
    ]
