# Generated by Django 5.2.8 on 2025-12-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_aboutyou_day_birth_remove_aboutyou_height_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutyou',
            options={'verbose_name': 'book', 'verbose_name_plural': 'books ab'},
        ),
    ]
