# Generated by Django 5.2.8 on 2025-12-05 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_aboutyou_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(choices=[('♥️', '♥️'), ('♥️♥️', '♥️♥️'), ('♥️♥️♥️', '♥️♥️♥️'), ('♥️♥️♥️♥️', '♥️♥️♥️♥️'), ('♥️♥️♥️♥️♥️', '♥️♥️♥️♥️♥️')], default='♥️♥️♥️♥️', verbose_name='choose marks')),
                ('text', models.TextField(verbose_name='enter review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='books.aboutyou')),
            ],
        ),
    ]
