# Generated by Django 5.2.8 on 2025-12-05 11:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='choose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='books.aboutyou', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='marks',
            field=models.IntegerField(choices=[(1, '♥️'), (2, '♥️♥️'), (3, '♥️♥️♥️'), (4, '♥️♥️♥️♥️'), (5, '♥️♥️♥️♥️♥️')], default=4, validators=[django.core.validators.MinValueValidator(1, message='Ставьте оценку только от 1 до 5'), django.core.validators.MaxValueValidator(5, message='Ставьте оценку только от 1 до 5')], verbose_name='choose marks'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(200, message='Минимум 200 символов!')], verbose_name='enter review'),
        ),
    ]
