# Generated by Django 5.2.8 on 2025-12-09 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_reviews_choose_alter_reviews_marks_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutYou',
            new_name='Books',
        ),
    ]
